# **Datetime Formats & Timezone Conversion**

## 📌 PROBLEM STATEMENT

***E-commerce company "ShopKaro" ke paas orders data hai multiple sources se – Website (IST), Mobile App (different timezones), API (UTC).*** 

**Date formats bhi mixed hain**:  
- "2024-01-15"  
- "15/01/2024"  
- "Jan 15, 2024"  

Hume sab dates ko standard IST format mein convert karna hai.

## 📌 BUSINESS USE

- ✅ Accurate hourly/daily sales analysis  
- ✅ Peak hours identify karna for marketing campaigns  
- ✅ SLA tracking – order to delivery time calculate karna  
- ✅ Revenue reporting – date-wise accurate calculation  
- ✅ Fraud detection – same customer multiple timezones se orders

In [2]:
data = {
    'order_id': ['ORD001', 'ORD002', 'ORD003', 'ORD004', 'ORD005', 'ORD006', 'ORD007', 'ORD008', 'ORD009', 'ORD010',
                 'ORD011', 'ORD012', 'ORD013', 'ORD014', 'ORD015', 'ORD016', 'ORD017', 'ORD018', 'ORD019', 'ORD020',
                 'ORD021', 'ORD022', 'ORD023', 'ORD024', 'ORD025', 'ORD026', 'ORD027', 'ORD028', 'ORD029', 'ORD030',
                 'ORD031', 'ORD032', 'ORD033', 'ORD034', 'ORD035'],
    
    'customer_name': ['Rajesh Kumar', 'Priya Sharma', 'John Smith', 'Sarah Johnson', 'Amit Patel',
                      'Emily Brown', 'Vikram Singh', 'Michael Chen', 'Sneha Reddy', 'David Lee',
                      'Ananya Iyer', 'Jessica Wang', 'Rahul Verma', 'Lisa Anderson', 'Karthik Menon',
                      'Robert Taylor', 'Divya Nair', 'Maria Garcia', 'Arjun Rao', 'Jennifer Martinez',
                      'Meera Joshi', 'James Wilson', 'Sanjay Desai', 'Patricia Moore', 'Kavya Pillai',
                      'Christopher Davis', 'Rohan Chopra', 'Linda Rodriguez', 'Nisha Agarwal', 'Daniel Hernandez',
                      'Aditya Khanna', 'Nancy Lewis', 'Shreya Malhotra', 'Thomas Walker', 'Varun Sinha'],
    
    'order_date_raw': ['2024-01-15 14:30:00',           # Standard format
                       '15/01/2024 09:45:30',           # DD/MM/YYYY format
                       'Jan 15, 2024 11:20 AM',         # Month name format
                       '2024-01-15T16:30:00Z',          # ISO format with Z (UTC)
                       '15-01-2024 18:45',              # DD-MM-YYYY format
                       '2024/01/16 08:30:00',           # YYYY/MM/DD format
                       '16-Jan-2024 14:15:30',          # DD-Mon-YYYY format
                       '01/16/2024 10:00:00',           # MM/DD/YYYY format (US)
                       '2024-01-16T12:30:00+05:30',     # ISO with IST timezone
                       None,                             # Missing date
                       '17.01.2024 15:45',              # DD.MM.YYYY format
                       '2024-01-17 20:30:00',           # Standard format
                       'January 17, 2024 09:00',        # Full month name
                       '2024-13-45 10:00:00',           # Invalid date (month 13)
                       '18/01/2024',                    # Only date, no time
                       '2024-01-18T08:30:00-08:00',     # ISO with PST timezone
                       '19 Jan 2024 11:30 AM',          # DD Mon YYYY format
                       '2024-01-19 22:15:00',           # Standard format
                       '20-01-2024',                    # DD-MM-YYYY (no time)
                       '2024/01/20 14:00:00',           # YYYY/MM/DD format
                       '',                               # Empty string
                       '21/01/2024 16:30:45',           # DD/MM/YYYY format
                       '2024-01-21T10:00:00+00:00',     # ISO UTC format
                       'Jan 22, 2024',                  # Month name (no time)
                       '22.01.2024 13:45:30',           # DD.MM.YYYY format
                       '2024-01-22T18:30:00-05:00',     # ISO with EST timezone
                       '23/01/2024 08:15',              # DD/MM/YYYY format
                       '2024-01-23 19:45:00',           # Standard format
                       '24-Jan-2024 10:30',             # DD-Mon-YYYY format
                       '01/24/2024 15:00:00',           # MM/DD/YYYY format
                       '2024-01-25T09:30:00+08:00',     # ISO with Singapore timezone
                       '25/01/2024 17:45:30',           # DD/MM/YYYY format
                       'January 25, 2024 12:00 PM',     # Full month name
                       '2024-01-26 14:30:00',           # Standard format
                       '27.01.2024'],                   # DD.MM.YYYY (no time)
    
    'timezone': ['IST', 'IST', 'UTC', 'UTC', 'IST', 'PST', 'EST', 'PST', 'IST', 'IST',
                 'UTC', 'IST', 'EST', 'IST', 'IST', 'PST', 'UTC', 'IST', 'IST', 'UTC',
                 'IST', 'IST', 'UTC', 'PST', 'IST', 'EST', 'IST', 'UTC', 'IST', 'PST',
                 'SGT', 'IST', 'EST', 'IST', 'IST'],
    
    'order_amount': [2500.00, 1800.50, 3200.00, 4500.75, 1200.00, 5600.00, 3400.25, 2800.50, 1900.00, 4200.00,
                     3100.75, 2700.00, 1500.50, 3800.00, 2200.25, 4100.00, 2900.50, 3500.75, 1600.00, 4800.00,
                     2100.25, 3300.00, 2600.50, 1400.75, 3900.00, 4400.25, 2000.00, 3700.50, 1700.75, 4600.00,
                     2400.25, 3000.00, 1300.50, 4300.75, 2800.00],
    
    'source': ['Website', 'Mobile App', 'Website', 'API', 'Mobile App', 'Website', 'Mobile App', 'API', 'Website', 'Mobile App',
               'API', 'Website', 'Mobile App', 'CSV Import', 'Website', 'API', 'Mobile App', 'Website', 'Mobile App', 'API',
               'CSV Import', 'Website', 'API', 'Mobile App', 'Website', 'API', 'Mobile App', 'Website', 'Mobile App', 'API',
               'Website', 'Mobile App', 'API', 'Website', 'Mobile App']
}

# **Importing Libraries**

In [3]:
import pandas as pd 
import numpy as np 
import pytz 
from datetime import datetime

# **Creating Data frame**

In [4]:
df = pd.DataFrame(data)
df.head()

,order_id,customer_name,order_date_raw,timezone,order_amount,source
0,ORD001,Rajesh Kumar,2024-01-15 14:30:00,IST,2500.00,Website
1,ORD002,Priya Sharma,15/01/2024 09:45:30,IST,1800.50,Mobile App
2,ORD003,John Smith,"Jan 15, 2024 11:20 AM",UTC,3200.00,Website
3,ORD004,Sarah Johnson,2024-01-15T16:30:00Z,UTC,4500.75,API
4,ORD005,Amit Patel,15-01-2024 18:45,IST,1200.00,Mobile App

In [5]:
date_formats =[
    '%Y-%m-%d %H:%M:%S',           # 2024-01-15 14:30:00
    '%d/%m/%Y %H:%M:%S',           # 15/01/2024 09:45:30
    '%b %d, %Y %I:%M %p',          # Jan 15, 2024 11:20 AM
    '%Y-%m-%dT%H:%M:%SZ',          # 2024-01-15T16:30:00Z
    '%d-%m-%Y %H:%M',              # 15-01-2024 18:45
    '%Y/%m/%d %H:%M:%S',           # 2024/01/16 08:30:00
    '%d-%b-%Y %H:%M:%S',           # 16-Jan-2024 14:15:30
    '%m/%d/%Y %H:%M:%S',           # 01/16/2024 10:00:00
    '%d.%m.%Y %H:%M',              # 17.01.2024 15:45
    '%B %d, %Y %H:%M',             # January 17, 2024 09:00
    '%d/%m/%Y',                    # 18/01/2024
    '%d %b %Y %I:%M %p',           # 19 Jan 2024 11:30 AM
    '%d-%m-%Y',                    # 20-01-2024
    '%b %d, %Y',                   # Jan 22, 2024
    '%d.%m.%Y %H:%M:%S',           # 22.01.2024 13:45:30
    '%d/%m/%Y %H:%M',              # 23/01/2024 08:15
    '%d-%b-%Y %H:%M',              # 24-Jan-2024 10:30
    '%B %d, %Y %I:%M %p',          # January 25, 2024 12:00 PM
    '%Y-%m-%d',                    # 2024-01-26
    '%d.%m.%Y'                     # 27.01.2024
]

In [43]:
def date_parsing(date_string,timezone_str ="IST"):
    if pd.isna(date_string) or date_string=="":
        return pd.NaT
    if isinstance(date_string,datetime):
        return date_string
    date_strng = str(date_string).strip()

    #YYYY-MM-DDTHH:MM:SSZ
    #YYYY-MM-DDTHH:MM:SS+05:30

    if "T" in date_strng and ("+" in date_strng or date_strng.endswith("Z")):
        try:
            dt = pd.to_datetime(date_strng,utc=True)
            ist = pytz.timezone('Asia/Kolkata')
            return dt.astimmezone(ist)
        except:
            pass

    for fmt in date_formats:
        try:
            dt = datetime.strptime(date_strng,fmt)
            tz_map = {
                'IST': 'Asia/Kolkata',
                'UTC': 'UTC',
                'PST': 'US/Pacific',
                'EST': 'US/Eastern',
                'SGT': 'Asia/Singapore'
            }
            source_tz = pytz.timezone(tz_map.get(timezone_str,'UTC'))
            date_with_tz = source_tz.localize(dt)
            ist = pytz.timezone('Asia/Kolkata')
            dt_ist = date_with_tz.astimezone(ist)
            return dt_ist
        except(ValueError,AttributeError):
            continue

In [44]:
df.head()

,order_id,customer_name,order_date_raw,timezone,order_amount,source
0,ORD001,Rajesh Kumar,2024-01-15 14:30:00,IST,2500.00,Website
1,ORD002,Priya Sharma,15/01/2024 09:45:30,IST,1800.50,Mobile App
2,ORD003,John Smith,"Jan 15, 2024 11:20 AM",UTC,3200.00,Website
3,ORD004,Sarah Johnson,2024-01-15T16:30:00Z,UTC,4500.75,API
4,ORD005,Amit Patel,15-01-2024 18:45,IST,1200.00,Mobile App

In [45]:
df["Order_With_IST"] = df.apply(
    lambda row : date_parsing(row["order_date_raw"],row["timezone"]),axis=1
)

In [46]:
df.head()

,order_id,customer_name,order_date_raw,timezone,order_amount,source,Order_With_IST
0,ORD001,Rajesh Kumar,2024-01-15 14:30:00,IST,2500.00,Website,2024-01-15 14:30:00+05:30
1,ORD002,Priya Sharma,15/01/2024 09:45:30,IST,1800.50,Mobile App,2024-01-15 09:45:30+05:30
2,ORD003,John Smith,"Jan 15, 2024 11:20 AM",UTC,3200.00,Website,2024-01-15 16:50:00+05:30
3,ORD004,Sarah Johnson,2024-01-15T16:30:00Z,UTC,4500.75,API,2024-01-15 22:00:00+05:30
4,ORD005,Amit Patel,15-01-2024 18:45,IST,1200.00,Mobile App,2024-01-15 18:45:00+05:30